export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE';

export const SEARCH_MOVIE_START_BY_ID = 'SEARCH_MOVIE_START_BY_ID';
export const SEARCH_MOVIE_ERROR_BY_ID = 'SEARCH_MOVIE_ERROR_BY_ID';
export const SEARCH_MOVIE_COMPLETE_BY_ID = 'SEARCH_MOVIE_COMPLETE_BY_ID';
